Repository IgnacioBarraza/BlackSharkWeb, pull requests merged in 2024-06, with the labels that each got.

#54 Feat/create equipment routes
  backend/app.ts
  backend/routes/equipmentRouter.ts
  backend/routes/galleryRouter.ts
  backend/routes/getData.ts
  backend/schemas/equipmentSchema.ts
  backend/schemas/projectSchema.ts
  backend/schemas/serviceSchema.ts
Labels: enhancement

#55 Feat/create collaboration routes
  backend/app.ts
  backend/routes/collabsRouter.ts
  backend/routes/getData.ts
  backend/schemas/collabsSchema.ts
Labels: enhancement

#56 Refactor/gallery
  backend/routes/galleryRouter.ts
  frontend/src/providers/backendContext.tsx
  frontend/src/providers/firebaseContext.tsx
  frontend/src/providers/userContext.tsx
  frontend/src/shared/gallery/components/imagemodal.tsx
  frontend/src/shared/gallery/components/uploadGalleryButton.tsx
  frontend/src/shared/gallery/components/uploadModal.tsx
  frontend/src/shared/gallery/gallery.tsx
  frontend/src/shared/services/components/uploadServiceModal.tsx
  frontend/src/shared/services/services.tsx
  frontend/src/styles/gallery.css
  frontend/src/utils/interfaces.ts
Labels: enhancement

#60 Feat/add new designs
  frontend/package-lock.json
  frontend/package.json
  frontend/public/homepage1.jpeg
  frontend/src/shared/homepage.tsx
  frontend/src/styles/homepage.css
Labels: enhancement

#63 Fix/add equipment data verification
  backend/schemas/equipmentSchema.ts
  frontend/src/shared/tools.tsx
  frontend/src/shared/toolscomponents/uploadToolsModal.tsx
Labels: bug

#66 Refactor/return ids from backend
  backend/app.ts
  backend/routes/budgetRouter.ts
  backend/routes/buymentRouter.ts
  backend/routes/campaignRouter.ts
  backend/routes/collabsRouter.ts
  backend/routes/inventoryRouter.ts
  backend/routes/mediaRouter.ts
  backend/routes/projectRouter.ts
  backend/routes/serviceRouter.ts
  backend/routes/shoppingCart.ts
  backend/schemas/budgetSchema.ts
  backend/schemas/buymentScema.ts
  backend/schemas/inventorySchema.ts
  backend/schemas/projectSchema.ts
Labels: refactor
