Repository IgnacioBarraza/BlackSharkWeb, pull requests merged in 2024-12, with the labels that each got.

#89 💚 Fix working directory of the github action to deploy on firebase
  .github/workflows/deploy.yml
Labels: bug

#91 Refactor/refactor login page
  public/logotipo_blacksharkstudios.webp
  src/auth/components/BSWImage.tsx
  src/auth/components/GoogleButton.tsx
  src/auth/components/showpassword.tsx
  src/auth/login.tsx
  src/auth/register.tsx
  src/components/RecoverPassword/components/recoverModal.tsx
  src/components/RecoverPassword/recoverpassword.tsx
  src/logos/Google.tsx
  src/utils/interfaces.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: refactor

#93 Refactor/services view
  components.json
  package-lock.json
  package.json
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/dialog.tsx
  src/components/ui/input.tsx
  src/components/ui/slider.tsx
  src/index.css
  src/lib/utils.ts
  src/shared/services/components/editServiceModal.tsx
  src/shared/services/components/selectedServiceModal.tsx
  src/shared/services/components/serviceGrid.tsx
  src/shared/services/components/serviceModal.tsx
  src/shared/services/components/uploadButton.tsx
  src/shared/services/components/uploadServiceModal.tsx
  src/shared/services/services.tsx
  src/utils/interfaces.ts
  src/utils/utils.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: refactor

#96 Refactor/routes n navbar
  .env.development
  package-lock.json
  package.json
  public/BlackShark.webp
  src/App.tsx
  src/auth/authLayout.tsx
  src/auth/login.tsx
  src/auth/register.tsx
  src/components/Footer/Footer.tsx
  src/components/NavBar/Navbar.tsx
  src/components/NavBar/components/desktopMenu.tsx
  src/components/NavBar/components/dropdownMenu.tsx
  src/components/NavBar/components/loggedFooter.tsx
  src/components/NavBar/components/mobileMenu.tsx
  src/components/NavBar/components/userDropdown.tsx
  src/components/NavBar/sidebar.tsx
  src/components/ui/button.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/separator.tsx
  src/components/ui/sheet.tsx
  src/components/ui/sidebar.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/tooltip.tsx
  src/hooks/use-mobile.tsx
  src/index.css
  src/layouts/accountLayout.tsx
  src/layouts/adminLayout.tsx
  src/layouts/homeLayout.tsx
  src/main.tsx
  src/providers/propsContext.tsx
  src/router/index.tsx
  src/routes/protectedRoute.tsx
  src/routes/routesConfig.tsx
  src/shared/account/account.tsx
  src/shared/admin/adminHomePage.tsx
  src/shared/contact.tsx
  src/shared/gallery/gallery.tsx
  src/shared/homepage.tsx
  src/shared/messageContact.tsx
  src/shared/metrics/metricsDashboard.tsx
  src/shared/notfound.tsx
  src/shared/services/services.tsx
  src/shared/shop/shoppingCart.tsx
  src/shared/tools/tools.tsx
  src/utils/interfaces.ts
  tailwind.config.js
Labels: enhancement, refactor

#94 feat: adding firebase google auth config
  .env.development
  .env.production
  package.json
  src/auth/components/GoogleButton.tsx
  src/auth/login.tsx
  src/components/NavBar/components/dropdownMenu.tsx
  src/firebase.ts
  src/providers/authContext.tsx
  src/providers/propsContext.tsx
  src/router/index.tsx
  src/utils/interfaces.ts
Labels: enhancement
